### ISSUE TITLE
SSL failure TLSv1 protocol version

### ISSUE THREAD

**Issue by dch** [jhaals/ansible-vault#15]
This seems similar to https://github.com/jhaals/ansible-vault/pull/3 

```
FAILED! => {"failed": true, "msg": "Unable to read secret/ansible from vault: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)>"}
```
- ansible v2.1.1.0 on OSX El Capitan installed via `brew install ansible`
- `tls_min_version = "tls12"` set in `vault.hcl` on servers (it's also the default now)
- python v2.7.12 via brew 
- vauilt 0.5.3 on FreeBSD 11/amd64 built with LibreSSL

The python version seems  up to date, any other suggestion how I could address this?

**Comment by bernielomax** [comment]
Im experiencing this too with Ansible's Kubernetes plugin. They do mention there is a validation bug. But I am hitting the same problem with validation turned off.

https://docs.ansible.com/ansible/kubernetes_module.html

**Comment by dch** [comment]
## root cause

via IRC:

>  the virtualenv we install ansible in to is constructed with system python, which uses apple's bad openssl; pyopenssl is installed and configured against homebrew's openssl but doesn't automatically replace the stdlib ssl module. requests should be using it; things in the stdlib probably are not.

Sadly ansible & therefore `vault.py` is at the mercy of this arcane mess, and effectively pulls in the crippled OSX OpenSSL, `OpenSSL 0.9.8zh 14 Jan 2016`, instead of the desired brewed version `OpenSSL 1.0.2h  3 May 2016` that we need to have TLS1.2 support.

## solution
- in `/usr/local/Library/Taps/homebrew/homebrew-core/Formula/ansible.rb` [L20](https://github.com/Homebrew/homebrew-core/blob/master/Formula/ansible.rb#L20) change to depend on brewed python 100% of the time: `depends_on :python` and not just for snow leopard
- rebuild the dependencies from source

``` shell
brew update
brew upgrade openssl
brew cleanup
brew rm --force python ansible
brew install --build-from-source python
brew install --build-from-source ansible
```

In `vault.py` we need a single change, just after generating the context in https://github.com/jhaals/ansible-vault/blob/master/vault.py#L66 :

``` python
        # homebrew's ansible setup is quirky so let's lock to TLS1.2 only
        # https://docs.python.org/dev/library/ssl.html
        context.options = ssl.PROTOCOL_TLSv1_2
```

The issue is that for users with a different SSL, this might actually be `ssl.PROTOCOL_TLS` or `ssl.PROTOCOLv23` instead for older ones. I don't know if using `ssl.OPENSSL_VERSION` as a string to check against against is sensible, any better suggestions?

**Comment by dch** [comment]
@bernielomax I am pretty sure your certificate validation issue in kubernetes is unrelated BTW

**Comment by dch** [comment]
https://github.com/Homebrew/brew-evolution/pull/12 hopefully should resolve this in future

**Comment by VFagundes** [comment]
I've installed python via brew
then

installed pip via sudo easy_install

`sudo easynstall pip`
