### ISSUE TITLE
Reading and writing files from Vault

### ISSUE THREAD

**Issue by AndreaCrotti** [jhaals/ansible-vault#29]
First of all, thanks for nice plugin!

Then, I was trying to do the following thing:
- store a ssh key into vault (which works just by using the @file syntax with vault read)
- look that up with ansible-vault
- with an ansible task write that out to another file

Any idea about how it can be done?
In theory I just need to store the key as a string and then write it to file, but could not find a way to do that yet..
Thanks

**Comment by jhaals** [comment]
Sorry for the extremely slow reply, I had notifications of for some time and this got lost.
Please reopen if this is problem still.
Writing content to a file is described in the readme.
