### ISSUE TITLE
Error while looking up from playbook

### ISSUE THREAD

**Issue by uzzz** [jhaals/ansible-vault#30]
Hi, 

I inserted line from README into my playbook

```
- debug: msg="{{ lookup('vault', 'secret/foo', 'value') }}"
```

Bu I receive following error:
`Unexpected error in during lookup: run() got multiple values for keyword argument 'inject'`

Ansible 1.9.6

Am I doing something wrong or it's a bug?

**Comment by jhaals** [comment]
Sorry for the extremely slow reply, I had notifications disabled for some time and your issue got lost.
Please reopen if this issue still remains, I'm no longer running 1.9 myself but there has been some community contributions that might have solved this issue.
