### ISSUE TITLE
Allow to iterate over list of secrets not values

### ISSUE THREAD

**Issue by ketchoop** [jhaals/ansible-vault#40]
Is there any possibility to do it? E.g. I have two users in ```secret/users``` path and want to get their secrets and want to do it dynamically. I know, that I can define array with users or curl to get list of users from vault, but it's not convenient.

**Comment by jhaals** [comment]
It's not possible to iterate. Not sure it's possible to do it in a nice way in lookup functions. I have no plans on adding it currently. Sorry for the late reply.
