### ISSUE TITLE
Quoted parameters should not be split on spaces

### ISSUE THREAD

**Issue by ajrgrubbs** [jhaals/ansible-vault#48]
Example:

`lookup('vault', 'my/arbitrary/path param="My short sentence"')`

This would resolve `param` to be `"My`. (Then an index error occurs when resolving the next term, so nothing is submitted)

I think this should be an easy fix using the `shlex` module's `split()` method. I'd be happy to submit a PR but I'd like your input first.

**Comment by jhaals** [comment]
Sounds like a good idea to support quoted parameters 👍 👍
