### ISSUE TITLE
Install instructions?

### ISSUE THREAD

**Issue by b-long** [jhaals/ansible-vault#50]
Hi @jhaals , great plugin!

Would you mind adding some content to the README describing the install process?

**Comment by jhaals** [comment]
Hi, thanks!

I'll try to add some instructions in a week or two(vacation)

**Comment by b-long** [comment]
Cool, I appreciate it 😄 👍 Looking forward to it.

**Comment by b-long** [comment]
I just figured out one of the many installation options and wanted to propose a "hello world" solution.

1) Create an ansible.cfg file next to a given playbook (e.g. print-secret.yml) :
```shell
$ cat ansible.cfg 
[defaults]
lookup_plugins = ./lookup_plugins
```
2) Create a folder to hold your lookup plugins:
```shell
$ mkdir lookup_plugins/
```
3) Clone this plugin into the directory
```shell
$ cd lookup_plugins/
$ git clone https://github.com/jhaals/ansible-vault.git
```
4) Use the plugin.

----
Here's an example playbook:
```yml
---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

  - name: Get a secret from Vault
    debug: msg="{{ lookup('vault', 'secret/digitalocean-api-key', 'value') }}"
```
Run it as normal: `ansible-playbook print-secret.yml`, and you'll get the following output:
```
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [Get a secret from Vault] *************************************************
ok: [localhost] => {
    "msg": "7872q4cfff396de2c1x7d052bfec4b0d4"
}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```

Truthfully, my opinion is that Ansible itself doesn't explain plugin installation very well.  For instance, I think such a description should be more obvious on this page: https://docs.ansible.com/ansible/latest/intro_configuration.html
