### ISSUE TITLE
merge with hashi_vault in core ansible

### ISSUE THREAD

**Issue by dch** [jhaals/ansible-vault#6]
super plugin thank-you are you also aware of https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/lookup/hashi_vault.py merging yours into core ansible would be a huge win IMO

**Comment by jhaals** [comment]
Thanks @dch! 

Quoting myself from the vault mailing list.

> The hashi_vault plugin has some downsides, it has dependencies and can't handle dynamic secrets nor does it take VAULT_TOKEN from env.
> I submitted a PR which gives the same functionality without dependencies https://github.com/ansible/ansible/pull/13907 It's tagged for the 2.1 milestone. I might update the PR with support for dynamic secrets but that will break compatibility with earlier 2.0 versions. I believe it's better to have the module outside core, it allow frequent updates and better flexibility since the module can be included in your config repo.
