### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by lukasmrtvy** [jhaals/ansible-vault#8]
Is possible to use environment variables in ansible playbook? Just like my example?
Because i cant get it work...

```
- hosts: localhost
  vars:
    vault1_env:
      VAULT_ADDR: https://localhost:8200/
      VAULT_TOKEN: my-token-id
      VAULT_SKIP_VERIFY: True

  tasks:
     - debug: msg="{{ lookup('vault', 'secret/hello', 'value') }}"
     - shell: echo VAULT_ADDR is $VAULT_ADDR, VAULT_TOKEN is $VAULT_TOKEN, VAULT_SKIP_VERIFY is $VAULT_SKIP_VERIFY
       environment: "{{ vault1_env }}"
       register: shellout
     - debug: var=shellout

```

**Comment by justinlarose** [comment]
If you figure this out, please reply back to the thread. I'm actually trying to do this as well.

**Comment by sidick** [comment]
Can you use the environment option?

e.g.
```
- hosts: localhost
  environment:
    VAULT_ADDR: 'https://localhost:8200/
```
or something?

**Comment by sidick** [comment]
Correcting my previous comment, surely you need to use environment: in the first debug command too?

Edit: hmm, see what you mean, complains about in VAULT_ADDR variable here too

**Comment by jennymorton** [comment]
For host that is running the playbooks {{ lookup('env','HOME') }}
For remote hosts  {{ lookup('ansible_env','HOME') }}

To export the environment, required to use vault, in a secure way:
```bash
vaultExportEnvironment () {
    export VAULT_ADDR=http://127.0.0.1:8200
    echo "Vault token (will be hidden):"
    stty_orig=`stty -g`
    stty -echo
    read vault_token
    stty $stty_orig

    export VAULT_TOKEN=$vault_token
}
```

**Comment by richfromm** [comment]
The issue is that when you're setting environment variables like this, you are setting them on the remote host. The environment variables that control Vault need to be set on the deploy (local) host.

As of #27, you can now set `vault_addr`, `vault_cacert`, and `vault_capath` as Ansible variables.

Note that vault_token is explicitly left out of that list.  However, as of #25 you can now set that via the file `~/.vault_token`

**Comment by jhaals** [comment]
I consider this to be fixed thanks to @richfromm
